default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: localhost
  port: 5432

development:
  <<: *default
  database: movie_app

test:
  <<: *default
  database: movie_app_test

production:
  <<: *default
  database: movie_app_production
